version: '3'

services:
  srsepc:
    container_name: srsepc01
    build: .
    volumes:
      - /bin:/bin
      - /etc:/etc 
      - /lib:/lib 
      - /var:/var 
      - /lib64:/lib64 
      - /sbin:/sbin 
      - /sys:/sys 
      - /usr:/usr
 #   ports:
 #     - "2152:2152/udp"
 #     - "2123:2123/udp"
 #   networks:
 #     core01:
 #       ipv4_address: 10.50.1.2
    tty: true
    stdin_open: true
    privileged: true

#networks:
#  core01:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 10.50.1.0/24
