
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: srslte
  name: srslte-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srslte
  template:
    metadata:
      labels:
        app: srslte
    spec:
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - srslte
#            topologyKey: kubernetes.io/hostname
#      publicIP: 10.244.1.50
      hostname: enb
#      hostNetwork: true
      containers:
      - image: srslte-enb
#      - image: cloudorc/vcore-mme:latest
        name: srslte-enb-container
        imagePullPolicy: IfNotPresent

        command: ['/bin/sh', 'launcher.sh', '10.244.5.3']
#        command: ['/bin/sh', '/docker-entrypoint/deploy-test.sh']
      # This sets how evenly spread the pods
      # For example, if there are 3 nodes available,
      # 2 pods are scheduled for each node.

        securityContext:
          capabilities:
            add:
              - NET_ADMIN
          privileged: true
      affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                          - key: app
                            operator: In
                            values:
                            - srslte-enb-container
                      topologyKey: kubernetes.io/hostname
          