
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: srslte
  name: srslte-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: srslte
  template:
    metadata:
      labels:
        app: srslte
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - srslte
              topologyKey: topology.kubernetes.io/hostname
#      publicIP: 10.244.1.50
      hostname: enb
#      hostNetwork: true
      containers:
      - image: srslte-enb
#      - image: cloudorc/vcore-mme:latest
        name: srslte-enb-container
        imagePullPolicy: IfNotPresent
#        ports:
#        - containerPort: 2000-50000
#          protocol:
#          - TCP
#          - UDP
#          - SCTP
        command: ['/bin/sh', 'launcher.sh', '10.244.5.3']
#        command: ['/bin/sh', '/docker-entrypoint/deploy-test.sh']
      # This sets how evenly spread the pods
      # For example, if there are 3 nodes available,
      # 2 pods are scheduled for each node.

        securityContext:
          capabilities:
            add:
              - NET_ADMIN
          privileged: true

      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule