apiVersion: apps/v1
kind: Deployment
metadata:
  name: epc-deployment
  labels:
    app: srs-epc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epc
  template:
    metadata:
      labels:
        app: epc
    spec:
      containers:
      - name: epc
        image: srslte_k8s_srsepc
        imagePullPolicy: Never
#        ports:
#        - containerPort: 80
